name: "Build Go Container"
on:
  push:
    branches:
      - master

env:
  VERSION_NUMBER: 1.18
  IMAGE_NAME: go

jobs:
  build_image:
    name: "Build"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: go
    steps:
      - name: "Checkout Repository"
        uses: actions/checkout@v2

      - name: "Build Container"
        run: docker build . --tag app_image

      - name: "Login to GitHub Packages Docker Registry"
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: "Tag and Push Images"
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository }}-$IMAGE_NAME
          docker tag app_image $IMAGE_ID:latest
          docker tag app_image $IMAGE_ID:$VERSION_NUMBER
          docker push $IMAGE_ID:latest
          docker push $IMAGE_ID:$VERSION_NUMBER